export { default as IconFacebook } from './IconFacebook.vue'
export { default as IconInstagram } from './IconInstagram.vue'
export { default as IconYoutube } from './IconYoutube.vue'
export { default as IconMenu } from './IconMenu.vue'
export { default as IconChevronDown } from './IconChevronDown.vue'
export { default as IconClose } from './IconClose.vue'
